language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"

node_js:
  - "10"

services:
  - redis-server
  - docker

before_install:
  - git clone https://github.com/mxcube/mx3docker.git mx3docker
  - docker build --no-cache -t mxcube3-backend mx3docker/demo/mxcube3/mxcube3_debian9/

install:
  - npm install
  - npm run build

  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then travis_retry pip install -r requirements.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3'* ]]; then travis_retry pip install -r requirements-py3.txt; fi

script:
  - python -m pytest